### ISSUE TITLE
Institute admin tool 

### ISSUE THREAD

**Issue by gperu** [softwaresaved/fellowms#12]
Even though this started as a project for the administration of the Fellowship Programme, I think it could/should extend to the wider administration of, at least, the financial transations of the Edinburgh branch of the Institue.

**Comment by rgaiacs** [comment]
> Even though this started as a project for the administration of the Fellowship Programme, I think it could/should extend to the wider administration of, at least, the financial transations of the Edinburgh branch of the Institue.

@gperu Just let me know of what I need to add.
