### ISSUE TITLE
Fellows dashboard

### ISSUE THREAD

**Issue by gperu** [softwaresaved/fellowms#14]
Moc-up: https://docs.google.com/drawings/d/11TI9-NpU4mznFlAUG1w9OpXwDw7KXxPgy713q0V2s3I/edit

My idea is that this is an individualised dashboard (one for each Fellow).

It needs to be discussed the how to grant access to it.

**Comment by rgaiacs** [comment]
@gperu I'm closing this. We will improve when fellows make suggestions.
