### ISSUE TITLE
Statuses of an expenses claim (EC)

### ISSUE THREAD

**Issue by gperu** [softwaresaved/fellowms#16]
Received: it means that an EC has been received and added to the DB via the app (usually by the Project Office)

Processed: it means that an EC has been processed (by the Project Office) and passed to the authoriser (the Director)

Authorised: it means that an EC has been authorised and is now in the hands of Accounts

**Comment by rgaiacs** [comment]
@gperu I defined

```
EXPENSE_STATUS = (
        ('W', 'Not submitted yet'),
        ('S', 'Submitted (but not processed yet)'),
        ('P', 'Processing'),
        ('A', 'Approved (waiting reply from finances)'),
        ('F', 'Finished'),
)
```

Do you want that I change it based on your first comment?
